# Generated by Django 4.0.4 on 2022-05-06 02:46

import django.core.validators
from django.db import migrations, models
import wines.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Red_Wines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_name', models.CharField(max_length=50)),
                ('vineyard', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=50)),
                ('year', models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(3000))),
                ('light_bold', models.IntegerField(verbose_name=wines.models.Red_Wines.scale)),
                ('sweet_dry', models.IntegerField(verbose_name=wines.models.Red_Wines.scale)),
                ('smooth_tanic', models.IntegerField(verbose_name=wines.models.Red_Wines.scale)),
                ('soft_acidic', models.IntegerField(verbose_name=wines.models.Red_Wines.scale)),
            ],
        ),
    ]
