# Generated by Django 4.0.4 on 2022-05-06 02:53

import django.core.validators
from django.db import migrations, models
import wines.models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='White_Wines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_name', models.CharField(max_length=50)),
                ('vineyard', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=50)),
                ('year', models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(3000))),
                ('light_bold', models.IntegerField(verbose_name=wines.models.White_Wines.scale)),
                ('sweet_dry', models.IntegerField(verbose_name=wines.models.White_Wines.scale)),
                ('herbaceous_zesty', models.IntegerField(verbose_name=wines.models.White_Wines.scale)),
            ],
        ),
    ]
