# Generated by Django 4.0.4 on 2022-05-06 03:01

import django.core.validators
from django.db import migrations, models
import wines.models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0002_white_wines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='white_wines',
            name='herbaceous_zesty',
            field=models.IntegerField(null=True, verbose_name=wines.models.White_Wines.scale),
        ),
        migrations.AlterField(
            model_name='white_wines',
            name='light_bold',
            field=models.IntegerField(null=True, verbose_name=wines.models.White_Wines.scale),
        ),
        migrations.AlterField(
            model_name='white_wines',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='white_wines',
            name='style',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='white_wines',
            name='sweet_dry',
            field=models.IntegerField(null=True, verbose_name=wines.models.White_Wines.scale),
        ),
        migrations.AlterField(
            model_name='white_wines',
            name='vineyard',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='white_wines',
            name='wine_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='white_wines',
            name='year',
            field=models.IntegerField(null=True, verbose_name=django.core.validators.MaxValueValidator(3000)),
        ),
    ]
