# Generated by Django 4.0.4 on 2022-05-06 15:31

import django.core.validators
from django.db import migrations, models
import wines.models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0003_alter_white_wines_herbaceous_zesty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='red_wines',
            name='light_bold',
            field=models.IntegerField(null=True, verbose_name=wines.models.Red_Wines.scale),
        ),
        migrations.AlterField(
            model_name='red_wines',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='red_wines',
            name='smooth_tanic',
            field=models.IntegerField(null=True, verbose_name=wines.models.Red_Wines.scale),
        ),
        migrations.AlterField(
            model_name='red_wines',
            name='soft_acidic',
            field=models.IntegerField(null=True, verbose_name=wines.models.Red_Wines.scale),
        ),
        migrations.AlterField(
            model_name='red_wines',
            name='style',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='red_wines',
            name='sweet_dry',
            field=models.IntegerField(null=True, verbose_name=wines.models.Red_Wines.scale),
        ),
        migrations.AlterField(
            model_name='red_wines',
            name='vineyard',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='red_wines',
            name='wine_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='red_wines',
            name='year',
            field=models.IntegerField(null=True, verbose_name=django.core.validators.MaxValueValidator(3000)),
        ),
    ]
